resources:
  pipelines:

    # ── Pipeline 1: Landing Zone ─────────────────────────
    lzn_junction_bloodwork:
      name:        "ch-lzn-dlt-pipeline-junction-bloodwork-${var.env}"
      catalog:     "${var.catalog}"
      schema:      "lzn_junction_bloodwork"             # ← changed from target

      development: false
      continuous:  false
      channel:     CURRENT
      photon:      true
      serverless:  true

      libraries:
        - notebook:
            path: ../notebooks/lzn_dlt_junction_bloodwork.py

      configuration:
        catalog:     "${var.catalog}"
        schema:      "lzn_junction_bloodwork"
        volume_name: "${var.volume_name}"
        env:         "${var.env}"

      tags:
        tenant: "ch"

    # ── Pipeline 2: Raw / Bronze Zone ────────────────────
    raw_junction_bloodwork:
      name:        "ch-raw-dlt-pipeline-junction-bloodwork-${var.env}"
      catalog:     "${var.catalog}"
      schema:      "raw_junction_bloodwork"             # ← changed from target

      development: false
      continuous:  false
      channel:     CURRENT
      photon:      true
      serverless:  true

      libraries:
        - notebook:
            path: ../notebooks/raw_dlt_junction_bloodwork.py

      configuration:
        catalog:     "${var.catalog}"
        schema:      "raw_junction_bloodwork"
        volume_name: "${var.volume_name}"
        env:         "${var.env}"

      tags:
        tenant: "ch"